<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Produk;
use App\Models\Pembeli;
use App\Models\Supplier;
use App\Models\TransaksiPenjualan;
use App\Models\TransaksiPembelian;

class DatabaseSeeder extends Seeder
{
    public function run()
    {
        // Seeder for users (ID auto-generated by Laravel)
        $adminUser = User::create([
            'nama' => 'Igno',
            'email' => 'igno@yahoo.com',
            'password' => bcrypt('igno6969'),
            'peran' => 'admin',
        ]);

        $cashierUser = User::create([
            'nama' => 'Rayy',
            'email' => 'Raey@gmail.com',
            'password' => bcrypt('raey478'),
            'peran' => 'cashier',
        ]);

        // Seeder for products
        $produk1 = Produk::create([
            'nama' => 'Oreo',
            'harga' => 10000.00,
            'jumlah_stock' => 50,
        ]);

        $produk2 = Produk::create([
            'nama' => 'Roti Tawar',
            'harga' => 20000.00,
            'jumlah_stock' => 30,
        ]);

        // Seeder for buyers (Pembeli)
        $pembeli1 = Pembeli::create([
            'user_id' => $cashierUser->id,   // Uses cashier user ID
            'nama' => 'Ucup',
            'email' => 'ucup69@example.com',
            'nomor_telepon' => '1234567890',
            'alamat' => '123 Main St',
        ]);

        $pembeli2 = Pembeli::create([
            'user_id' => $cashierUser->id,   // Uses cashier user ID
            'nama' => 'Anton',
            'email' => 'anton420@example.com',
            'nomor_telepon' => '0987654321',
            'alamat' => '456 Elm St',
        ]);

        // Seeder for suppliers (Supplier)
        Supplier::create([
            'user_id' => $adminUser->id,   // Uses admin user ID
            'nama' => 'Susup',
            'contact' => 'susu@example.com',
            'alamat' => '789 Oak St',
        ]);

        Supplier::create([
            'user_id' => $adminUser->id,   // Uses admin user ID
            'nama' => 'Sasap',
            'contact' => 'sasa@example.com',
            'alamat' => '101 Pine St',
        ]);

        // Seeder for transaksi penjualan (Sales transaction)
        $transaksiPenjualan = TransaksiPenjualan::create([
            'user_id' => $cashierUser->id,    // The cashier managing the sale
            'pembeli_id' => $pembeli1->id,    // Link to a specific buyer (Ucup)
            'total' => 30000.00,              // Total price of the transaction
        ]);

        // Attach products to this transaction (many-to-many)
        $transaksiPenjualan->produk()->attach([
            $produk1->id => ['jumlah' => 2],  // 2 Oreo
            $produk2->id => ['jumlah' => 1],  // 1 Roti Tawar
        ]);

        // Seeder for transaksi pembelian (Purchase transaction)
        $transaksiPembelian = TransaksiPembelian::create([
            'user_id' => $adminUser->id,      // Admin managing the purchase
            'supplier_id' => 1,               // ID of supplier (for example)
            'total' => 50000.00,              // Total price of the purchase
        ]);

        // Attach products to this transaction (many-to-many)
        $transaksiPembelian->produk()->attach([
            $produk1->id => ['jumlah' => 10], // 10 Oreo purchased
            $produk2->id => ['jumlah' => 5],  // 5 Roti Tawar purchased
        ]);
    }
}

